#!/bin/sh
set -x
clang++ -I/usr/local/Cellar/opencv/2.4.7.1/include/ -I/usr/local/include/ -I./include/ -L/usr/local/lib --std=c++11 -lboost_system -lboost_filesystem `pkg-config --libs opencv` matching-w-freak.cpp -o search_server